### ISSUE TITLE
Inconsistent versioning between dependent and its dependency 

### ISSUE THREAD

**Issue by romatallinn** [fasten-project/fasten#302] opened 2021-08-25 23:16 UTC
## Describe the bug

Sometimes resolve dependents and resolve dependencies on artifact and its resulted dependent may result in inconsistent package versions.

For example,

- **A version a** depends on **B version b**;
- When we resolve dependents of **B version b**, we get **A version a**;
- But when we resolve dependencies of **A version a**, we get **B version c**, while we expect it to be **B version b**.

## To Reproduce
1. [Dependents of com.fasterxml.jackson.core:jackson-databind/2.8.11.3](https://api.fasten-project.eu/api/mvn/packages/com.fasterxml.jackson.core:jackson-databind/2.8.11.3/resolve/dependents) contains `com.tokbox:opentok-server-sdk/4.4.1`
2. But [dependencies of com.tokbox:opentok-server-sdk/4.4.1](https://api.fasten-project.eu/api/mvn/packages/com.tokbox:opentok-server-sdk/4.4.1/resolve/dependencies) contains `com.fasterxml.jackson.core:jackson-databind/2.12.1`.

## Expected behavior
In the second step, we expect com.fasterxml.jackson.core:jackson-databind to be of version `2.8.11.3`, since it's just a reverse of the first step.

**Comment by proksch** [comment] 2022-01-30 00:01
Yeah, I guess there is nothing we can do here, this is how Maven is resolving dependencies. Works as intended.

**Closed by proksch** 2022-01-30 00:01 UTC
Labels: bug, Priority: Low
