### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal character in path at index 

### ISSUE THREAD

**Issue by cg122** [fasten-project/fasten#169] opened 2020-12-09 09:49 UTC
## Describe the bug
'java.lang.IllegalArgumentException: Illegal character in path at index' when using JavaCGOpal command line tool in both COORD and FILE mode

## To Reproduce

1.  run command with options as below to merge call graph:
```
-a org.apache.commons:commons-text:1.9 -i COORD -m -ma CHA -d org.apache.commons:commons-lang3:3.11 -o merge_coordinate_result.json
```
or download 'commons-text-1.9.jar' and `commons-lang3-3.11.jar` then run command below:
```
-a commons-text-1.9.jar -i FILE -m -ma CHA -d commons-lang3-3.11.jar -o merge_coordinate_result.json
```

## Expected behavior
Generate raw and resolved call graph for artefact.

## Logs
```
[2020-12-09 10:29:56,422] [INFO ] [main] [e.f.a.j.d.MavenCoordinate$MavenResolver] - [ARTIFACT-DOWNLOAD] [SUCCESS] [685i] [org.apache.commons:commons-lang3:3.11] [NONE] Artifact retrieved from repo: https://repo.maven.apache.org/maven2/
[2020-12-09 10:30:02,429] [INFO ] [main] [e.f.a.j.Main] - Generated the call graph in 6,712 seconds.
[2020-12-09 10:30:02,466] [INFO ] [main] [e.f.c.m.CallGraphUtils] - Writing graph to merge_coordinate_result.json
[2020-12-09 10:30:02,865] [INFO ] [main] [e.f.a.j.d.MavenCoordinate$MavenResolver] - [ARTIFACT-DOWNLOAD] [SUCCESS] [211i] [org.apache.commons:commons-text:1.9] [NONE] Artifact retrieved from repo: https://repo.maven.apache.org/maven2/
[2020-12-09 10:30:03,490] [INFO ] [main] [e.f.a.j.Main] - Generated the call graph in 0,836 seconds.
[2020-12-09 10:30:03,498] [INFO ] [main] [e.f.c.m.CallGraphUtils] - Writing graph to merge_coordinate_result.json
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Illegal character in path at index 52: /org.apache.commons.text.lookup/StringLookupFactory$<clinit>()V:54$Lambda.%3Cclinit%3E()%2Fjava.lang%2FVoidType
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
	at eu.fasten.core.merge.LocalMerger.mergeWithCHA(LocalMerger.java:154)
	at eu.fasten.analyzer.javacgopal.Main.merge(Main.java:226)
	at eu.fasten.analyzer.javacgopal.Main.runMerge(Main.java:190)
	at eu.fasten.analyzer.javacgopal.Main.run(Main.java:154)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at eu.fasten.analyzer.javacgopal.Main.main(Main.java:140)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 52: /org.apache.commons.text.lookup/StringLookupFactory$<clinit>()V:54$Lambda.%3Cclinit%3E()%2Fjava.lang%2FVoidType
	at java.base/java.net.URI.create(URI.java:883)
	at eu.fasten.core.data.FastenURI.create(FastenURI.java:117)
	at eu.fasten.core.merge.LocalMerger.resolveInitsAndConstructors(LocalMerger.java:303)
	at eu.fasten.core.merge.LocalMerger.lambda$mergeWithCHA$0(LocalMerger.java:170)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.net.URISyntaxException: Illegal character in path at index 52: /org.apache.commons.text.lookup/StringLookupFactory$<clinit>()V:54$Lambda.%3Cclinit%3E()%2Fjava.lang%2FVoidType
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
	at java.base/java.net.URI$Parser.parse(URI.java:3125)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	... 13 more
```
## Environment (please complete the following information):
 - OS: Mac OS
 - Java version: 11

## Additional context
JavaCGOpal command line tool build with [commit](https://github.com/fasten-project/fasten/commit/74dbe44bbaf7652608043b13a9d1c6b3f3f08a70) in `develop` branch

**Comment by amottier** [comment] 2020-12-09 10:30
I looks like a duplicate of #168.

**Comment by cg122** [comment] 2020-12-22 10:54
Yes, I think it is a duplicate to #167 and #168

**Comment by ashkboos** [comment] 2020-12-23 13:54
8e40cbc

**Comment by ashkboos** [comment] 2020-12-23 13:55
@cg122 Would you please check if the problem still exists?

**Comment by cg122** [comment] 2020-12-23 14:55
@ashkboos Thanks. No exception now for the above tested example.

**Closed** 2020-12-23 14:59 UTC
Labels: Priority: High, bug
