### ISSUE TITLE
The Postgres database contains bogus dependency information

### ISSUE THREAD

**Issue by vigna** [fasten-project/fasten#311] opened 2021-10-11 15:41 UTC
The postgres database on monster is supposed to contain dependency information. However, for example, the query
```
select * from package_versions join packages on packages.id=package_versions.package_id where package_name like '%webgraph%' order by package_versions.created_at;
```

returns

```
 276268 |     158910 | 3.6.6   | OPAL         |                     -1 |              | 2020-10-30 10:36:19 | {"commitTag": "", "sourcesUrl": "", "packagingType": "jar", "parentCoordinate": "", "dependencyManagement": {"dependencies": []}}                                                                                            | 158910 | it.unimi.dsi:webgraph     | mvn   |              |            |
 206816 |     502471 | 3.6.2   | OPAL         |                     -1 |              | 2020-10-30 13:04:37 | {"commitTag": "", "sourcesUrl": "", "packagingType": "jar", "parentCoordinate": "", "dependencyManagement": {"dependencies": []}}                                                                                            | 502471 | it.unimi.dsi:webgraph-big | mvn   |              |            |
  23087 |     158910 | 3.6.7   | OPAL         |                     -1 |              | 2020-11-05 08:55:26 | {"commitTag": "", "sourcesUrl": "https://repo.maven.apache.org/maven2/it/unimi/dsi/webgraph/3.6.7/webgraph-3.6.7-sources.jar", "packagingType": "jar", "parentCoordinate": "", "dependencyManagement": {"dependencies": []}} | 158910 | it.unimi.dsi:webgraph     | mvn   |              |            |
 355063 |     502471 | 3.6.3   | OPAL         |                     -1 |              | 2020-11-08 22:00:40 | {"commitTag": "", "sourcesUrl": "", "packagingType": "jar", "parentCoordinate": "", "dependencyManagement": {"dependencies": []}}                                                                                            | 502471 | it.unimi.dsi:webgraph-big | mvn   |              |            |
 303815 |     158910 | 3.6.8   | OPAL         |                     -1 |              | 2020-11-28 16:15:04 | {"commitTag": "", "sourcesUrl": "", "packagingType": "jar", "parentCoordinate": "", "dependencyManagement": {"dependencies": []}}                                                                                            | 158910 | it.unimi.dsi:webgraph     | mvn   |              |            |
  99618 |     502471 | 3.6.4   | OPAL         |                     -1 |              | 2020-11-28 17:03:12 | {"commitTag": "", "sourcesUrl": "", "packagingType": "jar", "parentCoordinate": "", "dependencyManagement": {"dependencies": []}}                                                                                            | 502471 | it.unimi.dsi:webgraph-big | mvn   |              |            |
 592143 |     158910 | 3.6.9   | OPAL         |                     -1 |              | 2020-12-22 09:35:39 | {"commitTag": "", "sourcesUrl": "", "packagingType": "jar", "parentCoordinate": "", "dependencyManagement": {"dependencies": []}}                                                                                            | 158910 | it.unimi.dsi:webgraph     | mvn   |              |            |
 707767 |     502471 | 3.6.5   | OPAL         |                     -1 |              | 2020-12-22 10:19:15 | {"commitTag": "", "sourcesUrl": "", "packagingType": "jar", "parentCoordinate": "", "dependencyManagement": {"dependencies": []}}                                                                                            | 502471 | it.unimi.dsi:webgraph-big | mvn   |              |            |
 625464 |     158910 | 3.6.10  | OPAL         |                     -1 |              | 2021-01-31 17:33:46 | {"commitTag": "", "sourcesUrl": "", "packagingType": "jar", "parentCoordinate": "", "dependencyManagement": {"dependencies": []}}                                                                                            | 158910 | it.unimi.dsi:webgraph     | mvn   |              |            |
 753417 |     502471 | 3.6.6   | OPAL         |                     -1 |              | 2021-01-31 18:14:43 | {"commitTag": "", "sourcesUrl": "", "packagingType": "jar", "parentCoordinate": "", "dependencyManagement": {"dependencies": []}}                                                                                            | 502471 | it.unimi.dsi:webgraph-big | mvn   |              |            |
```

All these webgraph revisions have extensive lists of dependencies: nonetheless, none is recorded in the database.  Correspondingly, GraphMavenResolver does not return any dependency for these revisions.

In particular, 3.6.10 and all its dependencies appear in the database, as they have been downloaded using the Maven plugin. But the result of GraphMavenResolver is the same—no dependencies.

**Comment by vigna** [comment] 2021-10-21 08:06
OK, following the discussion in the 21 October call it turns out that information is also stored in the dependencies table. So there is apparently missing information in that table.

**Comment by vigna** [comment] 2021-10-21 08:23
After further testing, the dependency information for webgraph 3.6.10 appears to be in the table—it is just not returned by GraphMavenResolver.

**Comment by mir-am** [comment] 2021-11-03 09:52
To give an update, we've made some fixes to POMAnlyzer in #321. Also, there is some consideration for the server network configs to have many TCP connections, given that POMAnalyzer downloads many POM files in a short time.
I will inform the partners this Thu. on our dev call about the dependency info after the fixes.

**Comment by mir-am** [comment] 2021-11-17 12:36
POMAnalyzer with the recent fixes has been running for a week and I can confirm that there is much more dependency information in the `metadata` field of the dependency table. Also, #321 will be merged today.

**Comment by vigna** [comment] 2021-11-17 14:36
That's good, but now the dependencies are not in the graph database. For example, for webgraph 3.6.10 we get correctly the list of dependencies, but then:

```
2021-11-17 15:33:33,735 69943 INFO [main] e.f.c.m.CGMerger - For 16 dependencies failed to retrieve 10 graph data and 1 metadata from rocks db.
```

This is using `/mnt/fasten/graphdb/`. How are we supposed to have the dependencies indexed? Using the Maven plugin? Will it insert data in the new database?

**Comment by proksch** [comment] 2021-11-17 15:07
Ah, wait a second, I mixed up the two plugins... you are not talking about the `CallableIndex` in the Rocks DB, but the dependency graph. Are you referring to Mihail's in-memory representation that contains all dependencies/versions? AFAIK, this should be automatically rebuilt by restarting the REST API... or do we have yet another database?

**Comment by vigna** [comment] 2021-11-17 15:10
No no, the problem is the CallableIndex. When you try to create a merged graph for webgraph 3.6.10 you can read the message above. That message is caused by the fact the CallableIndex (formerly known as graphdb) does not contains data for the revisions contained in the dependency set of webgraph (which is stored by Postgres).

**Comment by proksch** [comment] 2021-11-17 15:16
Yeah, we renamed the database... we have so many graph related concepts in the project that we decided that it helps understandability to pick a name that reflects the content rather then the representation.

Regarding the CallableIndex, it might be that the pipeline does not execute the later steps right now and that, therefore, the new information has not been added to the index yet... I remember that @mir-am mentioned something about disabling one step to prevent redundant execution, but this might have the observed (unwanted) side-effect.

@mir-am Am I right in my interpretation or do you think this is caused by something else? If yes, could we please re-enable the whole pipeline to make sure that we end up with consistent information across all databases?

**Comment by proksch** [comment] 2021-11-17 15:20
As the error message is pointing to `CGMerger`, maybe @ashkboos is also able to share some insights into this issue.

**Comment by mir-am** [comment] 2021-11-17 16:12
> Yeah, we renamed the database... we have so many graph related concepts in the project that we decided that it helps understandability to pick a name that reflects the content rather then the representation.
> 
> Regarding the CallableIndex, it might be that the pipeline does not execute the later steps right now and that, therefore, the new information has not been added to the index yet... I remember that @mir-am mentioned something about disabling one step to prevent redundant execution, but this might have the observed (unwanted) side-effect.
> 
> @mir-am Am I right in my interpretation or do you think this is caused by something else? If yes, could we please re-enable the whole pipeline to make sure that we end up with consistent information across all databases?

My speculation is that this is probably due to the fact that OPAL is disabled and therefore subsequent plug-ins have not processed new records. I have stopped OPAL to prevent redundant execution as POMAnalyzer is re-processing its records.
By re-enabling the whole pipeline, the described issue by @vigna might be resolved. I will do this ASAP.

**Comment by vigna** [comment] 2021-11-18 08:59
As it turned out, the database `/mnt/fasten/graphdb` that I mentioned above was not the right one. Trying again the same merge with `/mnt/fasten/callable-index` gives

```
2021-11-18 09:52:45,392 118469 INFO [main] e.f.c.m.CGMerger - For 16 dependencies failed to retrieve 2 graph data and 7 metadata from rocks db.
```

This is a big progress in terms of graph covering, but why are 7 pieces of metadata missing? They're supposed to be written in parallel with graph data.

Is there maybe also here some exception that's being swallowed? Possibly there's some bug in our code that writes metadata but it's not being detected.

Of course, while the metadata issue is important we must understand also why there are 2 missing graphs in a set of dependencies that theoretically has been processed. Let us know if you can help with testing.

**Comment by proksch** [comment] 2021-11-22 15:39
My understanding is that the second half of the pipeline has been stopped by @mir-am so the callable index did not recompute the information... To the best of my knowledge, the plugins have been restarted now, but obviously need to process all packages to update the data.

@mir-am Is there anything else that needs to be done to make the metadata appear in the callable index?

**Comment by mir-am** [comment] 2021-11-22 16:07
> My understanding is that the second half of the pipeline has been stopped by @mir-am so the callable index did not recompute the information... To the best of my knowledge, the plugins have been restarted now, but obviously need to process all packages to update the data.
> 
> @mir-am Is there anything else that needs to be done to make the metadata appear in the callable index?

AFAIK, No! The whole pipeline is online now with the newest version of the FASTEN server.

**Comment by proksch** [comment] 2021-11-22 18:18
Ok. Could you please monitor the progress and check whether metadata starts to appear in the callable index? If not, we still have to fix something else...

**Comment by mir-am** [comment] 2021-11-22 19:31
@vigna @proksch
Today, Mehdi and I had a session to investigate this issue.
In short, we have found that the CallableIndexer plug-in swallows exceptions. Because it does NOT have a `.err` topic.
Also, the metadata DB plug-in writes non-existent graph paths to its output topic! 
During our session, we have found a particular example, which we'll use to debug the issue and propose a fix ASAP.

**Comment by proksch** [comment] 2021-11-22 19:51
Great find. I am not sure whether we should be happy to have found the issue or scared that such a fundamental issue managed to stay undetected for so long. :/ Please take care of this as soon as possible and make sure that we can resolve this issue for good.

**Comment by mir-am** [comment] 2021-11-24 13:48
> As it turned out, the database `/mnt/fasten/graphdb` that I mentioned above was not the right one. Trying again the same merge with `/mnt/fasten/callable-index` gives
> 
> ```
> 2021-11-18 09:52:45,392 118469 INFO [main] e.f.c.m.CGMerger - For 16 dependencies failed to retrieve 2 graph data and 7 metadata from rocks db.
> ```
> 
> This is a big progress in terms of graph covering, but why are 7 pieces of metadata missing? They're supposed to be written in parallel with graph data.
> 
> Is there maybe also here some exception that's being swallowed? Possibly there's some bug in our code that writes metadata but it's not being detected.
> 
> Of course, while the metadata issue is important we must understand also why there are 2 missing graphs in a set of dependencies that theoretically has been processed. Let us know if you can help with testing.

@vigna
1) To give an update, we found that a lot of metadata output files are indeed missing on the filesystem due to a minor issue in the deployment file. It's now fixed and unfortunately we need to re-run the metadata and callable-indexer again.

2) After investigating the issue with `webgraph@3.6.10`, we found 11 dependencies. Of which, 4 do not have metadata. On other hand, according to the posted logs above, there are 16 dependencies and 7 missing metadata. It would be great if you could provide a minimal example for reproducing the issue.

FYI, here is the SQL query we use to find dependencies for `webgraph@3.6.10` on Postgres:
```sql
;WITH dep AS (SELECT d.dependency_id, d.version_range from packages pkg, package_versions pkg_v, dependencies d 
 WHERE pkg.id = pkg_v.package_id
 AND d.package_version_id = pkg_v.id
 AND pkg.package_name = 'it.unimi.dsi:webgraph'
 AND pkg_v.version = '3.6.10')
 SELECT p.package_name, pv."version" FROM packages p, package_versions pv, dep d WHERE
 p.id = d.dependency_id AND
 pv.package_id =p.id AND
 pv."version" = SUBSTRING(CAST(d.version_range AS TEXT), 2, LENGTH(CAST(d.version_range as TEXT))-2);
```

**Comment by proksch** [comment] 2021-11-24 14:43
> ... It would be great if you could provide a minimal example ...

Maybe it is enough to just elaborate a bit more on how the numbers have been generated to make sure we can replicate them.

**Comment by proksch** [comment] 2021-11-24 14:45
> ... missing on the filesystem due to a minor issue in the deployment file ...

I would say the issue is rather major and was a pain to debug. The fix just happens to be a tiny change to the deployment file. ;)

**Comment by vigna** [comment] 2021-11-24 15:02
> 2. After investigating the issue with `webgraph@3.6.10`, we found 11 dependencies. Of which, 4 do not have metadata. On other hand, according to the posted logs above, there are 16 dependencies and 7 missing metadata. It would be great if you could provide a minimal example for reproducing the issue.
> 
> FYI, here is the SQL query we use to find dependencies for `webgraph@3.6.10` on Postgres:
> 
> ```sql
> ;WITH dep AS (SELECT d.dependency_id, d.version_range from packages pkg, package_versions pkg_v, dependencies d 
>  WHERE pkg.id = pkg_v.package_id
>  AND d.package_version_id = pkg_v.id
>  AND pkg.package_name = 'it.unimi.dsi:webgraph'
>  AND pkg_v.version = '3.6.10')
>  SELECT p.package_name, pv."version" FROM packages p, package_versions pv, dep d WHERE
>  p.id = d.dependency_id AND
>  pv.package_id =p.id AND
>  pv."version" = SUBSTRING(CAST(d.version_range AS TEXT), 2, LENGTH(CAST(d.version_range as TEXT))-2);
> ```

But this is not the way you find dependencies. This is how you can find the direct dependency set.

Please look at the wiki: https://github.com/fasten-project/fasten/wiki/Resolution-and-Stitching

**Comment by vigna** [comment] 2021-11-24 15:07
> It would be great if you could provide a minimal example for reproducing the issue.

Looks like there was some confusion between the dependency set and the resolved dependencies. In any case, in the `integration` branch there's a `eu.fasten.core.search.Example` class. If you run it, e.g.,

```
java eu.fasten.core.search.Example 625464 jdbc:postgresql://monster:5432/fasten_java fastenro /mnt/fasten/callable-index/ resolver.graph
```

you'll get

```
[...]
2021-11-24 16:05:53,102 81107 INFO [main] e.f.c.m.CGMerger - For 16 dependencies failed to retrieve 2 graph data and 7 metadata from rocks db.
```

**Comment by mir-am** [comment] 2021-11-24 16:28
> > ... It would be great if you could provide a minimal example ...
> 
> Maybe it is enough to just elaborate a bit more on how the numbers have been generated to make sure we can replicate them.

This is how we obtained 11 dependencies with 4 missing metadata files:
1) We query the metadata DB using the above SQL example to get dependencies for `webgraph@3.6.10`.
2) For each retrieved dependency, we check whether its metadata file exists on the file system.
This procedure was implemented in a simple Python script.

**Comment by vigna** [comment] 2021-11-24 18:43
> This is how we obtained 11 dependencies with 4 missing metadata files:
> 
> 1. We query the metadata DB using the above SQL example to get dependencies for `webgraph@3.6.10`.

As I already explained, this will give you the just dependency set. To merge a revision with its dependencies, you need a merged resolved dependency graph, which contains also dependencies of dependencies, recursively, where conflicts have been resolved. Please have a look at the wiki documentation above. Merging a graph just with its dependency set does not make any sense.

**Comment by proksch** [comment] 2021-11-30 13:29
@mir-am With your recent changes, is this issue still relevant?

**Comment by vigna** [comment] 2021-11-30 14:14
We are keeping constantly an eye on the DB and we are seeing it's slowly getting populated. So something good is happening. It is difficult to say now whether all is good.

**Comment by mir-am** [comment] 2021-11-30 17:32
> @mir-am With your recent changes, is this issue still relevant?

I think yes. We should monitor the callable Indexer and merge #340 to develop. A "perfect" solution to this issue is to run the callable indexer and perhaps metadata DB plug-ins to make sure that all GID graphs are properly stored in RocksDB for all Maven packages in the KB.

**Comment by mir-am** [comment] 2022-02-04 18:09
This issue is fixed in the new POMAnalyzer.

**Closed by mir-am** 2022-02-04 18:09 UTC
Labels: bug
